// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9YlVsOD_egQVW6rTIzDdN3WG9GTWc9Zk',
    appId: '1:34917299276:web:e0d5a483d0f8b3c1dcf0e9',
    messagingSenderId: '34917299276',
    projectId: 'karata-e028c',
    authDomain: 'karata-e028c.firebaseapp.com',
    databaseURL: 'https://karata-e028c-default-rtdb.firebaseio.com',
    storageBucket: 'karata-e028c.firebasestorage.app',
    measurementId: 'G-2WMTXXHGFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxt6UsaJB47h72ZVPjRJYpZHRO4ngIJQ',
    appId: '1:34917299276:android:2ba0fd93c64836a2dcf0e9',
    messagingSenderId: '34917299276',
    projectId: 'karata-e028c',
    databaseURL: 'https://karata-e028c-default-rtdb.firebaseio.com',
    storageBucket: 'karata-e028c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpAbAvEZ_2XJ67rU2M7SFNUCPrBIiV5Yg',
    appId: '1:34917299276:ios:04e118d70230b1e1dcf0e9',
    messagingSenderId: '34917299276',
    projectId: 'karata-e028c',
    databaseURL: 'https://karata-e028c-default-rtdb.firebaseio.com',
    storageBucket: 'karata-e028c.firebasestorage.app',
    iosBundleId: 'com.example.crazygame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpAbAvEZ_2XJ67rU2M7SFNUCPrBIiV5Yg',
    appId: '1:34917299276:ios:04e118d70230b1e1dcf0e9',
    messagingSenderId: '34917299276',
    projectId: 'karata-e028c',
    databaseURL: 'https://karata-e028c-default-rtdb.firebaseio.com',
    storageBucket: 'karata-e028c.firebasestorage.app',
    iosBundleId: 'com.example.crazygame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9YlVsOD_egQVW6rTIzDdN3WG9GTWc9Zk',
    appId: '1:34917299276:web:ae7017198cb3164ddcf0e9',
    messagingSenderId: '34917299276',
    projectId: 'karata-e028c',
    authDomain: 'karata-e028c.firebaseapp.com',
    databaseURL: 'https://karata-e028c-default-rtdb.firebaseio.com',
    storageBucket: 'karata-e028c.firebasestorage.app',
    measurementId: 'G-JS0FJGG651',
  );

}