// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr0Tuak2QpzUVU6Cw80XuYivwpkWC5qMc',
    appId: '1:357008337257:web:1c62a78de45919763975f8',
    messagingSenderId: '357008337257',
    projectId: 'crazy-game-3c761',
    authDomain: 'crazy-game-3c761.firebaseapp.com',
    databaseURL: 'https://crazy-game-3c761-default-rtdb.firebaseio.com',
    storageBucket: 'crazy-game-3c761.firebasestorage.app',
    measurementId: 'G-S33P7TDFGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ-mgylQ9f5tiqKLzVdTh_hvMLEDNPFEI',
    appId: '1:357008337257:android:31edb26b040be94e3975f8',
    messagingSenderId: '357008337257',
    projectId: 'crazy-game-3c761',
    databaseURL: 'https://crazy-game-3c761-default-rtdb.firebaseio.com',
    storageBucket: 'crazy-game-3c761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPyiha3sjkBeVTmWndAyogmea3m0BZsM',
    appId: '1:357008337257:ios:0e7512cb72eeb9de3975f8',
    messagingSenderId: '357008337257',
    projectId: 'crazy-game-3c761',
    databaseURL: 'https://crazy-game-3c761-default-rtdb.firebaseio.com',
    storageBucket: 'crazy-game-3c761.firebasestorage.app',
    iosBundleId: 'com.example.crazygame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLPyiha3sjkBeVTmWndAyogmea3m0BZsM',
    appId: '1:357008337257:ios:0e7512cb72eeb9de3975f8',
    messagingSenderId: '357008337257',
    projectId: 'crazy-game-3c761',
    databaseURL: 'https://crazy-game-3c761-default-rtdb.firebaseio.com',
    storageBucket: 'crazy-game-3c761.firebasestorage.app',
    iosBundleId: 'com.example.crazygame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr0Tuak2QpzUVU6Cw80XuYivwpkWC5qMc',
    appId: '1:357008337257:web:82ce1f5ba29c0fb63975f8',
    messagingSenderId: '357008337257',
    projectId: 'crazy-game-3c761',
    authDomain: 'crazy-game-3c761.firebaseapp.com',
    databaseURL: 'https://crazy-game-3c761-default-rtdb.firebaseio.com',
    storageBucket: 'crazy-game-3c761.firebasestorage.app',
    measurementId: 'G-8PSCFECK5E',
  );
}
